// Code generated by MockGen. DO NOT EDIT.
// Source: maintainer/maintainer_manager_node.go

// Package maintainer is a generated GoMock package.
package maintainer

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEventBrokerDispatcherCounter is a mock of eventBrokerDispatcherCounter interface.
type MockEventBrokerDispatcherCounter struct {
	ctrl     *gomock.Controller
	recorder *MockEventBrokerDispatcherCounterMockRecorder
}

// MockEventBrokerDispatcherCounterMockRecorder is the mock recorder for MockEventBrokerDispatcherCounter.
type MockEventBrokerDispatcherCounterMockRecorder struct {
	mock *MockEventBrokerDispatcherCounter
}

// NewMockEventBrokerDispatcherCounter creates a new mock instance.
func NewMockEventBrokerDispatcherCounter(ctrl *gomock.Controller) *MockEventBrokerDispatcherCounter {
	mock := &MockEventBrokerDispatcherCounter{ctrl: ctrl}
	mock.recorder = &MockEventBrokerDispatcherCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventBrokerDispatcherCounter) EXPECT() *MockEventBrokerDispatcherCounterMockRecorder {
	return m.recorder
}

// GetDispatcherCount mocks base method.
func (m *MockEventBrokerDispatcherCounter) GetDispatcherCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDispatcherCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetDispatcherCount indicates an expected call of GetDispatcherCount.
func (mr *MockEventBrokerDispatcherCounterMockRecorder) GetDispatcherCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDispatcherCount", reflect.TypeOf((*MockEventBrokerDispatcherCounter)(nil).GetDispatcherCount))
}

// StopAcceptingRegistrations mocks base method.
func (m *MockEventBrokerDispatcherCounter) StopAcceptingRegistrations() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopAcceptingRegistrations")
}

// StopAcceptingRegistrations indicates an expected call of StopAcceptingRegistrations.
func (mr *MockEventBrokerDispatcherCounterMockRecorder) StopAcceptingRegistrations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAcceptingRegistrations", reflect.TypeOf((*MockEventBrokerDispatcherCounter)(nil).StopAcceptingRegistrations))
}
