// Code generated by MockGen. DO NOT EDIT.
// Source: downstreamadapter/sink/topicmanager/topic_manager.go

// Package topicmanager is a generated GoMock package.
package topicmanager

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTopicManager is a mock of TopicManager interface.
type MockTopicManager struct {
	ctrl     *gomock.Controller
	recorder *MockTopicManagerMockRecorder
}

// MockTopicManagerMockRecorder is the mock recorder for MockTopicManager.
type MockTopicManagerMockRecorder struct {
	mock *MockTopicManager
}

// NewMockTopicManager creates a new mock instance.
func NewMockTopicManager(ctrl *gomock.Controller) *MockTopicManager {
	mock := &MockTopicManager{ctrl: ctrl}
	mock.recorder = &MockTopicManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopicManager) EXPECT() *MockTopicManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTopicManager) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockTopicManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTopicManager)(nil).Close))
}

// CreateTopicAndWaitUntilVisible mocks base method.
func (m *MockTopicManager) CreateTopicAndWaitUntilVisible(ctx context.Context, topicName string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopicAndWaitUntilVisible", ctx, topicName)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTopicAndWaitUntilVisible indicates an expected call of CreateTopicAndWaitUntilVisible.
func (mr *MockTopicManagerMockRecorder) CreateTopicAndWaitUntilVisible(ctx, topicName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopicAndWaitUntilVisible", reflect.TypeOf((*MockTopicManager)(nil).CreateTopicAndWaitUntilVisible), ctx, topicName)
}

// GetPartitionNum mocks base method.
func (m *MockTopicManager) GetPartitionNum(ctx context.Context, topic string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPartitionNum", ctx, topic)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPartitionNum indicates an expected call of GetPartitionNum.
func (mr *MockTopicManagerMockRecorder) GetPartitionNum(ctx, topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPartitionNum", reflect.TypeOf((*MockTopicManager)(nil).GetPartitionNum), ctx, topic)
}
