// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/sink/kafka/admin.go

// Package kafka is a generated GoMock package.
package kafka

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAdmin is a mock of Admin interface.
type MockAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMockRecorder
}

// MockAdminMockRecorder is the mock recorder for MockAdmin.
type MockAdminMockRecorder struct {
	mock *MockAdmin
}

// NewMockAdmin creates a new mock instance.
func NewMockAdmin(ctrl *gomock.Controller) *MockAdmin {
	mock := &MockAdmin{ctrl: ctrl}
	mock.recorder = &MockAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmin) EXPECT() *MockAdminMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAdmin) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAdminMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAdmin)(nil).Close))
}

// CreateTopic mocks base method.
func (m *MockAdmin) CreateTopic(detail TopicDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockAdminMockRecorder) CreateTopic(detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockAdmin)(nil).CreateTopic), detail)
}

// GetBrokerConfig mocks base method.
func (m *MockAdmin) GetBrokerConfig(configName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrokerConfig", configName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBrokerConfig indicates an expected call of GetBrokerConfig.
func (mr *MockAdminMockRecorder) GetBrokerConfig(configName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrokerConfig", reflect.TypeOf((*MockAdmin)(nil).GetBrokerConfig), configName)
}

// GetTopicConfig mocks base method.
func (m *MockAdmin) GetTopicConfig(topicName, configName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicConfig", topicName, configName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTopicConfig indicates an expected call of GetTopicConfig.
func (mr *MockAdminMockRecorder) GetTopicConfig(topicName, configName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicConfig", reflect.TypeOf((*MockAdmin)(nil).GetTopicConfig), topicName, configName)
}

// GetTopicsMeta mocks base method.
func (m *MockAdmin) GetTopicsMeta(topics []string, ignoreTopicError bool) (map[string]TopicDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsMeta", topics, ignoreTopicError)
	ret0, _ := ret[0].(map[string]TopicDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicsMeta indicates an expected call of GetTopicsMeta.
func (mr *MockAdminMockRecorder) GetTopicsMeta(topics, ignoreTopicError interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsMeta", reflect.TypeOf((*MockAdmin)(nil).GetTopicsMeta), topics, ignoreTopicError)
}
