// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/ticdc/pkg/sink/kafka (interfaces: Factory,SyncProducer,AsyncProducer)

// Package kafka is a generated GoMock package.
package kafka

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/pingcap/ticdc/pkg/sink/codec/common"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// AdminClient mocks base method.
func (m *MockFactory) AdminClient(arg0 context.Context) (ClusterAdminClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminClient", arg0)
	ret0, _ := ret[0].(ClusterAdminClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminClient indicates an expected call of AdminClient.
func (mr *MockFactoryMockRecorder) AdminClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminClient", reflect.TypeOf((*MockFactory)(nil).AdminClient), arg0)
}

// AsyncProducer mocks base method.
func (m *MockFactory) AsyncProducer(arg0 context.Context) (AsyncProducer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsyncProducer", arg0)
	ret0, _ := ret[0].(AsyncProducer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AsyncProducer indicates an expected call of AsyncProducer.
func (mr *MockFactoryMockRecorder) AsyncProducer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsyncProducer", reflect.TypeOf((*MockFactory)(nil).AsyncProducer), arg0)
}

// SyncProducer mocks base method.
func (m *MockFactory) SyncProducer(arg0 context.Context) (SyncProducer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncProducer", arg0)
	ret0, _ := ret[0].(SyncProducer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncProducer indicates an expected call of SyncProducer.
func (mr *MockFactoryMockRecorder) SyncProducer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncProducer", reflect.TypeOf((*MockFactory)(nil).SyncProducer), arg0)
}

// MockSyncProducer is a mock of SyncProducer interface.
type MockSyncProducer struct {
	ctrl     *gomock.Controller
	recorder *MockSyncProducerMockRecorder
}

// MockSyncProducerMockRecorder is the mock recorder for MockSyncProducer.
type MockSyncProducerMockRecorder struct {
	mock *MockSyncProducer
}

// NewMockSyncProducer creates a new mock instance.
func NewMockSyncProducer(ctrl *gomock.Controller) *MockSyncProducer {
	mock := &MockSyncProducer{ctrl: ctrl}
	mock.recorder = &MockSyncProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncProducer) EXPECT() *MockSyncProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSyncProducer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSyncProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSyncProducer)(nil).Close))
}

// SendMessage mocks base method.
func (m *MockSyncProducer) SendMessage(arg0 string, arg1 int32, arg2 *common.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockSyncProducerMockRecorder) SendMessage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockSyncProducer)(nil).SendMessage), arg0, arg1, arg2)
}

// SendMessages mocks base method.
func (m *MockSyncProducer) SendMessages(arg0 string, arg1 int32, arg2 *common.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessages", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessages indicates an expected call of SendMessages.
func (mr *MockSyncProducerMockRecorder) SendMessages(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessages", reflect.TypeOf((*MockSyncProducer)(nil).SendMessages), arg0, arg1, arg2)
}

// MockAsyncProducer is a mock of AsyncProducer interface.
type MockAsyncProducer struct {
	ctrl     *gomock.Controller
	recorder *MockAsyncProducerMockRecorder
}

// MockAsyncProducerMockRecorder is the mock recorder for MockAsyncProducer.
type MockAsyncProducerMockRecorder struct {
	mock *MockAsyncProducer
}

// NewMockAsyncProducer creates a new mock instance.
func NewMockAsyncProducer(ctrl *gomock.Controller) *MockAsyncProducer {
	mock := &MockAsyncProducer{ctrl: ctrl}
	mock.recorder = &MockAsyncProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsyncProducer) EXPECT() *MockAsyncProducerMockRecorder {
	return m.recorder
}

// AsyncRunCallback mocks base method.
func (m *MockAsyncProducer) AsyncRunCallback(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsyncRunCallback", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AsyncRunCallback indicates an expected call of AsyncRunCallback.
func (mr *MockAsyncProducerMockRecorder) AsyncRunCallback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsyncRunCallback", reflect.TypeOf((*MockAsyncProducer)(nil).AsyncRunCallback), arg0)
}

// AsyncSend mocks base method.
func (m *MockAsyncProducer) AsyncSend(arg0 context.Context, arg1 string, arg2 int32, arg3 *common.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsyncSend", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AsyncSend indicates an expected call of AsyncSend.
func (mr *MockAsyncProducerMockRecorder) AsyncSend(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsyncSend", reflect.TypeOf((*MockAsyncProducer)(nil).AsyncSend), arg0, arg1, arg2, arg3)
}

// Close mocks base method.
func (m *MockAsyncProducer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAsyncProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAsyncProducer)(nil).Close))
}
