// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/sink/kafka/factory.go

// Package kafka is a generated GoMock package.
package kafka

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// Admin mocks base method.
func (m *MockFactory) Admin(ctx context.Context) (Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Admin", ctx)
	ret0, _ := ret[0].(Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Admin indicates an expected call of Admin.
func (mr *MockFactoryMockRecorder) Admin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Admin", reflect.TypeOf((*MockFactory)(nil).Admin), ctx)
}

// AsyncProducer mocks base method.
func (m *MockFactory) AsyncProducer(ctx context.Context) (AsyncProducer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsyncProducer", ctx)
	ret0, _ := ret[0].(AsyncProducer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AsyncProducer indicates an expected call of AsyncProducer.
func (mr *MockFactoryMockRecorder) AsyncProducer(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsyncProducer", reflect.TypeOf((*MockFactory)(nil).AsyncProducer), ctx)
}

// SyncProducer mocks base method.
func (m *MockFactory) SyncProducer(ctx context.Context) (SyncProducer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncProducer", ctx)
	ret0, _ := ret[0].(SyncProducer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncProducer indicates an expected call of SyncProducer.
func (mr *MockFactoryMockRecorder) SyncProducer(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncProducer", reflect.TypeOf((*MockFactory)(nil).SyncProducer), ctx)
}
