// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/sink/kafka/sarama_sync_producer.go

// Package kafka is a generated GoMock package.
package kafka

import (
	reflect "reflect"

	sarama "github.com/IBM/sarama"
	gomock "github.com/golang/mock/gomock"
)

// MocksaramaSyncClient is a mock of saramaSyncClient interface.
type MocksaramaSyncClient struct {
	ctrl     *gomock.Controller
	recorder *MocksaramaSyncClientMockRecorder
}

// MocksaramaSyncClientMockRecorder is the mock recorder for MocksaramaSyncClient.
type MocksaramaSyncClientMockRecorder struct {
	mock *MocksaramaSyncClient
}

// NewMocksaramaSyncClient creates a new mock instance.
func NewMocksaramaSyncClient(ctrl *gomock.Controller) *MocksaramaSyncClient {
	mock := &MocksaramaSyncClient{ctrl: ctrl}
	mock.recorder = &MocksaramaSyncClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksaramaSyncClient) EXPECT() *MocksaramaSyncClientMockRecorder {
	return m.recorder
}

// Brokers mocks base method.
func (m *MocksaramaSyncClient) Brokers() []*sarama.Broker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Brokers")
	ret0, _ := ret[0].([]*sarama.Broker)
	return ret0
}

// Brokers indicates an expected call of Brokers.
func (mr *MocksaramaSyncClientMockRecorder) Brokers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Brokers", reflect.TypeOf((*MocksaramaSyncClient)(nil).Brokers))
}

// Close mocks base method.
func (m *MocksaramaSyncClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MocksaramaSyncClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MocksaramaSyncClient)(nil).Close))
}

// MocksaramaSyncProducerClient is a mock of saramaSyncProducerClient interface.
type MocksaramaSyncProducerClient struct {
	ctrl     *gomock.Controller
	recorder *MocksaramaSyncProducerClientMockRecorder
}

// MocksaramaSyncProducerClientMockRecorder is the mock recorder for MocksaramaSyncProducerClient.
type MocksaramaSyncProducerClientMockRecorder struct {
	mock *MocksaramaSyncProducerClient
}

// NewMocksaramaSyncProducerClient creates a new mock instance.
func NewMocksaramaSyncProducerClient(ctrl *gomock.Controller) *MocksaramaSyncProducerClient {
	mock := &MocksaramaSyncProducerClient{ctrl: ctrl}
	mock.recorder = &MocksaramaSyncProducerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksaramaSyncProducerClient) EXPECT() *MocksaramaSyncProducerClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MocksaramaSyncProducerClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MocksaramaSyncProducerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MocksaramaSyncProducerClient)(nil).Close))
}

// SendMessage mocks base method.
func (m *MocksaramaSyncProducerClient) SendMessage(msg *sarama.ProducerMessage) (int32, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", msg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MocksaramaSyncProducerClientMockRecorder) SendMessage(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MocksaramaSyncProducerClient)(nil).SendMessage), msg)
}

// SendMessages mocks base method.
func (m *MocksaramaSyncProducerClient) SendMessages(msgs []*sarama.ProducerMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessages", msgs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessages indicates an expected call of SendMessages.
func (mr *MocksaramaSyncProducerClientMockRecorder) SendMessages(msgs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessages", reflect.TypeOf((*MocksaramaSyncProducerClient)(nil).SendMessages), msgs)
}
