// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.
package metrics

import "github.com/prometheus/client_golang/prometheus"

const (
	namespace = "ticdc"
	subsystem = "sink"
)

// Metrics for cloud storage sink
var (
	// CloudStorageWriteBytesCounter records the total number of bytes written to cloud storage.
	CloudStorageWriteBytesCounter = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_write_bytes_total",
		Help:      "Total number of bytes written to cloud storage",
	}, []string{"namespace", "changefeed"})

	// CloudStorageFileCounter records the number of files generated by cloud storage sink.
	CloudStorageFileCounter = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_file_count",
		Help:      "Total number of files managed by a cloud storage sink",
	}, []string{"namespace", "changefeed"})

	// CloudStorageFlushDurationHistogram records the latency distributions of flushLog.
	CloudStorageFlushDurationHistogram = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_flush_duration_seconds",
		Help:      "The latency distributions of flush storage by a cloud storage sink",
		Buckets:   prometheus.ExponentialBuckets(0.001, 2.0, 13), // 1ms ~ 4.096s
	}, []string{"namespace", "changefeed"})

	// CloudStorageDDLFlushDurationHistogram records DDL flush duration.
	CloudStorageDDLFlushDurationHistogram = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_ddl_flush_duration_seconds",
		Help:      "DDL flush duration for cloud storage sink",
		Buckets:   prometheus.ExponentialBuckets(0.001, 2.0, 13), // 1ms ~ 4.096s
	}, []string{"namespace", "changefeed"})

	// CloudStorageWorkerBusyRatio records the busy ratio of CloudStorage bgUpdateLog worker.
	CloudStorageWorkerBusyRatio = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: subsystem,
			Name:      "cloud_storage_worker_busy_ratio",
			Help:      "Busy ratio for cloud storage sink dml worker.",
		}, []string{"namespace", "changefeed", "id"})

	CloudStorageSpoolMemoryBytesGauge = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_spool_memory_bytes",
		Help:      "Current memory bytes used by cloud storage spool",
	}, []string{"namespace", "changefeed"})

	CloudStorageSpoolDiskBytesGauge = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_spool_disk_bytes",
		Help:      "Current disk bytes used by cloud storage spool",
	}, []string{"namespace", "changefeed"})

	CloudStoragePendingPostEnqueueGauge = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_pending_post_enqueue",
		Help:      "Current number of PostEnqueue callbacks waiting in cloud storage spool",
	}, []string{"namespace", "changefeed"})

	// CloudStorageSpillBytesHistogram records spilled batch sizes.
	CloudStorageSpillBytesHistogram = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_spill_bytes",
		Help:      "Byte distribution of encoded batches spilled into cloud storage spool files",
		Buckets:   prometheus.ExponentialBuckets(1024, 2.0, 20), // 1KiB ~ 512MiB
	}, []string{"namespace", "changefeed"})

	// CloudStorageLoadBytesHistogram records loaded batch sizes.
	CloudStorageLoadBytesHistogram = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_load_bytes",
		Help:      "Byte distribution of encoded batches loaded from cloud storage spool",
		Buckets:   prometheus.ExponentialBuckets(1024, 2.0, 20), // 1KiB ~ 512MiB
	}, []string{"namespace", "changefeed"})

	CloudStorageRotateCountCounter = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_rotate_total",
		Help:      "Total number of local spool segment rotations in cloud storage sink",
	}, []string{"namespace", "changefeed"})

	CloudStorageSpoolSegmentCountGauge = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_spool_segment_count",
		Help:      "Current number of live cloud storage spool segments",
	}, []string{"namespace", "changefeed"})

	CloudStoragePendingTablesGauge = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_pending_tables",
		Help:      "Current number of tables buffered in one cloud storage writer shard",
	}, []string{"namespace", "changefeed", "writer"})

	CloudStoragePendingEntriesGauge = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_pending_entries",
		Help:      "Current number of buffered entries in one cloud storage writer shard",
	}, []string{"namespace", "changefeed", "writer"})

	CloudStoragePendingBytesGauge = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_pending_bytes",
		Help:      "Current buffered bytes in one cloud storage writer shard before flush",
	}, []string{"namespace", "changefeed", "writer"})

	CloudStorageFlushCountCounter = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: subsystem,
		Name:      "cloud_storage_flush_total",
		Help:      "Total number of flush batches emitted by one cloud storage writer shard",
	}, []string{"namespace", "changefeed", "writer", "reason"})
)

// InitCloudStorageMetrics registers all metrics in this file.
func InitCloudStorageMetrics(registry *prometheus.Registry) {
	registry.MustRegister(CloudStorageWriteBytesCounter)
	registry.MustRegister(CloudStorageFileCounter)
	registry.MustRegister(CloudStorageFlushDurationHistogram)
	registry.MustRegister(CloudStorageDDLFlushDurationHistogram)
	registry.MustRegister(CloudStorageWorkerBusyRatio)
	registry.MustRegister(CloudStorageSpoolMemoryBytesGauge)
	registry.MustRegister(CloudStorageSpoolDiskBytesGauge)
	registry.MustRegister(CloudStoragePendingPostEnqueueGauge)
	registry.MustRegister(CloudStorageSpillBytesHistogram)
	registry.MustRegister(CloudStorageLoadBytesHistogram)
	registry.MustRegister(CloudStorageRotateCountCounter)
	registry.MustRegister(CloudStorageSpoolSegmentCountGauge)
	registry.MustRegister(CloudStoragePendingTablesGauge)
	registry.MustRegister(CloudStoragePendingEntriesGauge)
	registry.MustRegister(CloudStoragePendingBytesGauge)
	registry.MustRegister(CloudStorageFlushCountCounter)
}
