// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.1
// source: pkg/messaging/proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the type of the message, it is used to determine how to decode the message.
	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// from is the sender of the message.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// to is the receiver of the message.
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// topic is the destination of the message, it is used to route the message to the correct handler.
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// payload is the payload of the message.
	Payload [][]byte `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty"`
	// create_at is the unix timestamp in milliseconds recorded when the message is created on sender side.
	CreateAt      int64 `protobuf:"varint,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_messaging_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_messaging_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_messaging_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetPayload() [][]byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

var File_pkg_messaging_proto_message_proto protoreflect.FileDescriptor

const file_pkg_messaging_proto_message_proto_rawDesc = "" +
	"\n" +
	"!pkg/messaging/proto/message.proto\x12\x05proto\"\x8e\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x05 \x03(\fR\apayload\x12\x1b\n" +
	"\tcreate_at\x18\x06 \x01(\x03R\bcreateAt2F\n" +
	"\x0eMessageService\x124\n" +
	"\x0estreamMessages\x12\x0e.proto.Message\x1a\x0e.proto.Message(\x010\x01B\x13Z\x11./messaging/protob\x06proto3"

var (
	file_pkg_messaging_proto_message_proto_rawDescOnce sync.Once
	file_pkg_messaging_proto_message_proto_rawDescData []byte
)

func file_pkg_messaging_proto_message_proto_rawDescGZIP() []byte {
	file_pkg_messaging_proto_message_proto_rawDescOnce.Do(func() {
		file_pkg_messaging_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_messaging_proto_message_proto_rawDesc), len(file_pkg_messaging_proto_message_proto_rawDesc)))
	})
	return file_pkg_messaging_proto_message_proto_rawDescData
}

var file_pkg_messaging_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_messaging_proto_message_proto_goTypes = []any{
	(*Message)(nil), // 0: proto.Message
}
var file_pkg_messaging_proto_message_proto_depIdxs = []int32{
	0, // 0: proto.MessageService.streamMessages:input_type -> proto.Message
	0, // 1: proto.MessageService.streamMessages:output_type -> proto.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_messaging_proto_message_proto_init() }
func file_pkg_messaging_proto_message_proto_init() {
	if File_pkg_messaging_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_messaging_proto_message_proto_rawDesc), len(file_pkg_messaging_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_messaging_proto_message_proto_goTypes,
		DependencyIndexes: file_pkg_messaging_proto_message_proto_depIdxs,
		MessageInfos:      file_pkg_messaging_proto_message_proto_msgTypes,
	}.Build()
	File_pkg_messaging_proto_message_proto = out.File
	file_pkg_messaging_proto_message_proto_goTypes = nil
	file_pkg_messaging_proto_message_proto_depIdxs = nil
}
