// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/txnutil/gc/gc_manager.go

// Package gc is a generated GoMock package.
package gc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/pingcap/ticdc/pkg/common"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CheckStaleCheckpointTs mocks base method.
func (m *MockManager) CheckStaleCheckpointTs(keyspaceID uint32, changefeedID common.ChangeFeedID, checkpointTs common.Ts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStaleCheckpointTs", keyspaceID, changefeedID, checkpointTs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckStaleCheckpointTs indicates an expected call of CheckStaleCheckpointTs.
func (mr *MockManagerMockRecorder) CheckStaleCheckpointTs(keyspaceID, changefeedID, checkpointTs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStaleCheckpointTs", reflect.TypeOf((*MockManager)(nil).CheckStaleCheckpointTs), keyspaceID, changefeedID, checkpointTs)
}

// TryUpdateKeyspaceGCBarrier mocks base method.
func (m *MockManager) TryUpdateKeyspaceGCBarrier(ctx context.Context, keyspaceID uint32, keyspaceName string, checkpointTs common.Ts, forceUpdate bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryUpdateKeyspaceGCBarrier", ctx, keyspaceID, keyspaceName, checkpointTs, forceUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// TryUpdateKeyspaceGCBarrier indicates an expected call of TryUpdateKeyspaceGCBarrier.
func (mr *MockManagerMockRecorder) TryUpdateKeyspaceGCBarrier(ctx, keyspaceID, keyspaceName, checkpointTs, forceUpdate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryUpdateKeyspaceGCBarrier", reflect.TypeOf((*MockManager)(nil).TryUpdateKeyspaceGCBarrier), ctx, keyspaceID, keyspaceName, checkpointTs, forceUpdate)
}

// TryUpdateServiceGCSafePoint mocks base method.
func (m *MockManager) TryUpdateServiceGCSafePoint(ctx context.Context, checkpointTs common.Ts, forceUpdate bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryUpdateServiceGCSafePoint", ctx, checkpointTs, forceUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// TryUpdateServiceGCSafePoint indicates an expected call of TryUpdateServiceGCSafePoint.
func (mr *MockManagerMockRecorder) TryUpdateServiceGCSafePoint(ctx, checkpointTs, forceUpdate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryUpdateServiceGCSafePoint", reflect.TypeOf((*MockManager)(nil).TryUpdateServiceGCSafePoint), ctx, checkpointTs, forceUpdate)
}
