// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/messaging/message_center.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	messaging "github.com/pingcap/ticdc/pkg/messaging"
	node "github.com/pingcap/ticdc/pkg/node"
)

// MockMessageCenter is a mock of MessageCenter interface.
type MockMessageCenter struct {
	ctrl     *gomock.Controller
	recorder *MockMessageCenterMockRecorder
}

// MockMessageCenterMockRecorder is the mock recorder for MockMessageCenter.
type MockMessageCenterMockRecorder struct {
	mock *MockMessageCenter
}

// NewMockMessageCenter creates a new mock instance.
func NewMockMessageCenter(ctrl *gomock.Controller) *MockMessageCenter {
	mock := &MockMessageCenter{ctrl: ctrl}
	mock.recorder = &MockMessageCenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageCenter) EXPECT() *MockMessageCenterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessageCenter) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockMessageCenterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessageCenter)(nil).Close))
}

// DeRegisterHandler mocks base method.
func (m *MockMessageCenter) DeRegisterHandler(topic string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeRegisterHandler", topic)
}

// DeRegisterHandler indicates an expected call of DeRegisterHandler.
func (mr *MockMessageCenterMockRecorder) DeRegisterHandler(topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeRegisterHandler", reflect.TypeOf((*MockMessageCenter)(nil).DeRegisterHandler), topic)
}

// IsReadyToSend mocks base method.
func (m *MockMessageCenter) IsReadyToSend(target node.ID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReadyToSend", target)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReadyToSend indicates an expected call of IsReadyToSend.
func (mr *MockMessageCenterMockRecorder) IsReadyToSend(target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReadyToSend", reflect.TypeOf((*MockMessageCenter)(nil).IsReadyToSend), target)
}

// OnNodeChanges mocks base method.
func (m *MockMessageCenter) OnNodeChanges(arg0 map[node.ID]*node.Info) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnNodeChanges", arg0)
}

// OnNodeChanges indicates an expected call of OnNodeChanges.
func (mr *MockMessageCenterMockRecorder) OnNodeChanges(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNodeChanges", reflect.TypeOf((*MockMessageCenter)(nil).OnNodeChanges), arg0)
}

// RegisterHandler mocks base method.
func (m *MockMessageCenter) RegisterHandler(topic string, handler messaging.MessageHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterHandler", topic, handler)
}

// RegisterHandler indicates an expected call of RegisterHandler.
func (mr *MockMessageCenterMockRecorder) RegisterHandler(topic, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHandler", reflect.TypeOf((*MockMessageCenter)(nil).RegisterHandler), topic, handler)
}

// SendCommand mocks base method.
func (m *MockMessageCenter) SendCommand(cmd *messaging.TargetMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCommand", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCommand indicates an expected call of SendCommand.
func (mr *MockMessageCenterMockRecorder) SendCommand(cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCommand", reflect.TypeOf((*MockMessageCenter)(nil).SendCommand), cmd)
}

// SendEvent mocks base method.
func (m *MockMessageCenter) SendEvent(msg *messaging.TargetMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEvent", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEvent indicates an expected call of SendEvent.
func (mr *MockMessageCenterMockRecorder) SendEvent(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEvent", reflect.TypeOf((*MockMessageCenter)(nil).SendEvent), msg)
}

// MockMessageSender is a mock of MessageSender interface.
type MockMessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSenderMockRecorder
}

// MockMessageSenderMockRecorder is the mock recorder for MockMessageSender.
type MockMessageSenderMockRecorder struct {
	mock *MockMessageSender
}

// NewMockMessageSender creates a new mock instance.
func NewMockMessageSender(ctrl *gomock.Controller) *MockMessageSender {
	mock := &MockMessageSender{ctrl: ctrl}
	mock.recorder = &MockMessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSender) EXPECT() *MockMessageSenderMockRecorder {
	return m.recorder
}

// IsReadyToSend mocks base method.
func (m *MockMessageSender) IsReadyToSend(target node.ID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReadyToSend", target)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReadyToSend indicates an expected call of IsReadyToSend.
func (mr *MockMessageSenderMockRecorder) IsReadyToSend(target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReadyToSend", reflect.TypeOf((*MockMessageSender)(nil).IsReadyToSend), target)
}

// SendCommand mocks base method.
func (m *MockMessageSender) SendCommand(cmd *messaging.TargetMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCommand", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCommand indicates an expected call of SendCommand.
func (mr *MockMessageSenderMockRecorder) SendCommand(cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCommand", reflect.TypeOf((*MockMessageSender)(nil).SendCommand), cmd)
}

// SendEvent mocks base method.
func (m *MockMessageSender) SendEvent(msg *messaging.TargetMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEvent", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEvent indicates an expected call of SendEvent.
func (mr *MockMessageSenderMockRecorder) SendEvent(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEvent", reflect.TypeOf((*MockMessageSender)(nil).SendEvent), msg)
}

// MockMessageReceiver is a mock of MessageReceiver interface.
type MockMessageReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockMessageReceiverMockRecorder
}

// MockMessageReceiverMockRecorder is the mock recorder for MockMessageReceiver.
type MockMessageReceiverMockRecorder struct {
	mock *MockMessageReceiver
}

// NewMockMessageReceiver creates a new mock instance.
func NewMockMessageReceiver(ctrl *gomock.Controller) *MockMessageReceiver {
	mock := &MockMessageReceiver{ctrl: ctrl}
	mock.recorder = &MockMessageReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageReceiver) EXPECT() *MockMessageReceiverMockRecorder {
	return m.recorder
}

// DeRegisterHandler mocks base method.
func (m *MockMessageReceiver) DeRegisterHandler(topic string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeRegisterHandler", topic)
}

// DeRegisterHandler indicates an expected call of DeRegisterHandler.
func (mr *MockMessageReceiverMockRecorder) DeRegisterHandler(topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeRegisterHandler", reflect.TypeOf((*MockMessageReceiver)(nil).DeRegisterHandler), topic)
}

// RegisterHandler mocks base method.
func (m *MockMessageReceiver) RegisterHandler(topic string, handler messaging.MessageHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterHandler", topic, handler)
}

// RegisterHandler indicates an expected call of RegisterHandler.
func (mr *MockMessageReceiverMockRecorder) RegisterHandler(topic, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHandler", reflect.TypeOf((*MockMessageReceiver)(nil).RegisterHandler), topic, handler)
}
