// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.
package metrics

import "github.com/prometheus/client_golang/prometheus"

// Metrics for cloud storage sink
var (
	// CloudStorageFileCountCounter records the number of files generated by cloud storage sink.
	CloudStorageFileCountCounter = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: "ticdc",
		Subsystem: "sink",
		Name:      "cloud_storage_file_count",
		Help:      "Total number of files managed by a cloud storage sink",
	}, []string{getKeyspaceLabel(), "changefeed"})

	// CloudStorageFlushDurationHistogram records the latency distributions of flushLog.
	CloudStorageFlushDurationHistogram = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: "ticdc",
		Subsystem: "sink",
		Name:      "cloud_storage_flush_duration_seconds",
		Help:      "The latency distributions of flush storage by a cloud storage sink",
		Buckets:   prometheus.ExponentialBuckets(0.001, 2.0, 13),
	}, []string{getKeyspaceLabel(), "changefeed"})

	// CloudStorageWriterBusyRatio records the busy ratio of CloudStorage writer.
	CloudStorageWriterBusyRatio = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "ticdc",
			Subsystem: "sink",
			Name:      "cloud_storage_writer_busy_ratio",
			Help:      "Busy ratio for cloud storage sink dml writer.",
		}, []string{getKeyspaceLabel(), "changefeed", "id"})

	CloudStorageRawBytesGauge = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: "ticdc",
		Subsystem: "sink",
		Name:      "cloud_storage_raw_bytes",
		Help:      "Approximate size of unflushed DML events in cloud storage sink (based on DMLEvent.GetSize)",
	}, []string{getKeyspaceLabel(), "changefeed", "type"})

	CloudStorageEncodedBytesGauge = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: "ticdc",
		Subsystem: "sink",
		Name:      "cloud_storage_encoded_bytes",
		Help:      "Encoded size of unflushed DML events in cloud storage sink (sum of encoded message key/value bytes)",
	}, []string{getKeyspaceLabel(), "changefeed", "type"})
)

// initCloudStorageMetrics registers all metrics in this file.
func initCloudStorageMetrics(registry *prometheus.Registry) {
	registry.MustRegister(CloudStorageFileCountCounter)
	registry.MustRegister(CloudStorageFlushDurationHistogram)
	registry.MustRegister(CloudStorageWriterBusyRatio)
	registry.MustRegister(CloudStorageRawBytesGauge)
	registry.MustRegister(CloudStorageEncodedBytesGauge)
}
