// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/txnutil/gc/gc_client.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gc "github.com/tikv/pd/client/clients/gc"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetGCStatesClient mocks base method.
func (m *MockClient) GetGCStatesClient(keyspaceID uint32) gc.GCStatesClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGCStatesClient", keyspaceID)
	ret0, _ := ret[0].(gc.GCStatesClient)
	return ret0
}

// GetGCStatesClient indicates an expected call of GetGCStatesClient.
func (mr *MockClientMockRecorder) GetGCStatesClient(keyspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGCStatesClient", reflect.TypeOf((*MockClient)(nil).GetGCStatesClient), keyspaceID)
}

// UpdateServiceGCSafePoint mocks base method.
func (m *MockClient) UpdateServiceGCSafePoint(ctx context.Context, serviceID string, ttl int64, safePoint uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceGCSafePoint", ctx, serviceID, ttl, safePoint)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceGCSafePoint indicates an expected call of UpdateServiceGCSafePoint.
func (mr *MockClientMockRecorder) UpdateServiceGCSafePoint(ctx, serviceID, ttl, safePoint interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceGCSafePoint", reflect.TypeOf((*MockClient)(nil).UpdateServiceGCSafePoint), ctx, serviceID, ttl, safePoint)
}
