// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tikv/pd/client/clients/gc (interfaces: GCStatesClient)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	gc "github.com/tikv/pd/client/clients/gc"
)

// MockGCStatesClient is a mock of GCStatesClient interface.
type MockGCStatesClient struct {
	ctrl     *gomock.Controller
	recorder *MockGCStatesClientMockRecorder
}

// MockGCStatesClientMockRecorder is the mock recorder for MockGCStatesClient.
type MockGCStatesClientMockRecorder struct {
	mock *MockGCStatesClient
}

// NewMockGCStatesClient creates a new mock instance.
func NewMockGCStatesClient(ctrl *gomock.Controller) *MockGCStatesClient {
	mock := &MockGCStatesClient{ctrl: ctrl}
	mock.recorder = &MockGCStatesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCStatesClient) EXPECT() *MockGCStatesClientMockRecorder {
	return m.recorder
}

// DeleteGCBarrier mocks base method.
func (m *MockGCStatesClient) DeleteGCBarrier(arg0 context.Context, arg1 string) (*gc.GCBarrierInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGCBarrier", arg0, arg1)
	ret0, _ := ret[0].(*gc.GCBarrierInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGCBarrier indicates an expected call of DeleteGCBarrier.
func (mr *MockGCStatesClientMockRecorder) DeleteGCBarrier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGCBarrier", reflect.TypeOf((*MockGCStatesClient)(nil).DeleteGCBarrier), arg0, arg1)
}

// GetGCState mocks base method.
func (m *MockGCStatesClient) GetGCState(arg0 context.Context) (gc.GCState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGCState", arg0)
	ret0, _ := ret[0].(gc.GCState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGCState indicates an expected call of GetGCState.
func (mr *MockGCStatesClientMockRecorder) GetGCState(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGCState", reflect.TypeOf((*MockGCStatesClient)(nil).GetGCState), arg0)
}

// SetGCBarrier mocks base method.
func (m *MockGCStatesClient) SetGCBarrier(arg0 context.Context, arg1 string, arg2 uint64, arg3 time.Duration) (*gc.GCBarrierInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGCBarrier", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*gc.GCBarrierInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetGCBarrier indicates an expected call of SetGCBarrier.
func (mr *MockGCStatesClientMockRecorder) SetGCBarrier(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGCBarrier", reflect.TypeOf((*MockGCStatesClient)(nil).SetGCBarrier), arg0, arg1, arg2, arg3)
}
