#!/usr/bin/env bash

set -eu
export PS4='+$(basename ${BASH_SOURCE}):${LINENO}:'
set -x

if [ "$NEXT_GEN" = 1 ]; then
    run_cdc_cli changefeed -k "$KEYSPACE_NAME" "$@"
else
    run_cdc_cli changefeed "$@"
fi

set +x
