#!/usr/bin/env bash

if [ $# -lt 2 ]; then
	echo "Usage: check_pd_health <pd_host> <pd_port> <check_count>"
	exit 1
fi

host="$1"
port="$2"
check_count=${3:-60}

i=0
while ! curl -o /dev/null -sf "http://${host}:${port}/pd/api/v1/version"; do
	i=$((i + 1))
	if [ "$i" -gt "$check_count" ]; then
		echo 'Failed to start PD'
		exit 1
	fi
	sleep 1
done

i=0
while [ "$(curl http://${host}:${port}/pd/api/v1/health 2>/dev/null | jq '.[0].health')" != "true" ]; do
	i=$((i + 1))
	if [ "$i" -gt "$check_count" ]; then
		echo 'Failed to start PD'
		exit 1
	fi
	sleep 1
done
