#!/bin/bash
# Copyright 2026 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

repoRoot=$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)
kafkaDump="$repoRoot/bin/kafka_dump"

# Some test runners reuse prebuilt binaries without running integration_test_build.
if [ ! -x "$kafkaDump" ]; then
	make -C "$repoRoot" kafka_dump >&2
fi

exec "$kafkaDump" "$@"
