#!/bin/bash
#
# Copyright 2020 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

set -eux

# parameter 1: pd host
# parameter 2: pd port
pd_host=${1}
pd_port=${2}
is_tls=${3:-false}

max_retries=5
retry_interval=1
tso=""
protocol="http"
if [ "$is_tls" == "true" ]; then
	protocol="https"
fi
pd_addr="${protocol}://${pd_host}:${pd_port}"
for ((i = 1; i <= max_retries; i++)); do
	tso=$(run_cdc_cli tso query --pd="$pd_addr" | grep -v "Command to ticdc") || true

	# Check if we got a valid TSO (starts with a number)
	if [[ -n "$tso" && "$tso" =~ ^[0-9] ]]; then
		break
	fi

	if [[ $i -lt $max_retries ]]; then
		echo "TSO query attempt $i failed, retrying in ${retry_interval}s..." >&2
		sleep "$retry_interval"
	else
		echo "TSO query failed after $max_retries attempts" >&2
		exit 1
	fi
done

# make sure get tso only
# the tso got above is:
# "427768583921860609 PASS coverage: 2.7% of statements in github.com/pingcap/ticdc/..."
# and only "427768583921860609" is a real tso
echo $tso | awk -F " " '{print $1}'

set +x
