#!/bin/sh
# parameter 1: sql
# parameter 2: database host
# parameter 3: database port
# parameter 4: other mysql client settings

set -e

sql=${1}

host=127.0.0.1
if [ $# -gt 1 ]; then
	shift
	host=${1}
fi

port=4000
if [ $# -gt 1 ]; then
	shift
	port=${1}
fi

if [ $# -gt 1 ]; then
	shift
	other=${*}
fi

prepare="set global tidb_enable_clustered_index = 'int_only';"

echo "OUT_DIR: $OUT_DIR"
log_file="$OUT_DIR/sql_res.$TEST_NAME.log"

echo "[$(date)] Executing SQL: ${sql}" >>"$log_file"

mysql -uroot -h${host} -P${port} ${other} --default-character-set utf8mb4 -E -e "${prepare}" >>"$log_file"
mysql -uroot -h${host} -P${port} ${other} --default-character-set utf8mb4 -E -e "${sql}" >>"$log_file"
