#!/bin/bash

# Random DDL+DML weekly smoke test: slow downstream apply for lossy DDL (MySQL sink only).
#
# Timeline (high level):
#   1) start_tidb_cluster: start upstream + downstream TiDB.
#   2) random_ddl_test_runner bootstrap: create identical schemas and deterministic seed data on both sides.
#   3) start TiCDC (single capture) with a failpoint that delays downstream DDL execution.
#   4) random_ddl_test_runner workload: run concurrent random DML + random DDL on upstream.
#   5) Final diff: sync_diff_inspector compares upstream vs downstream using diff_config.toml generated by the runner.
#
# Notes:
#   - This case requires MySQL sink and sets GO_FAILPOINTS to delay MySQL sink DDL execution.

set -eu

CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source $CUR/../_utils/test_prepare

WORK_DIR=$OUT_DIR/$TEST_NAME
CDC_BINARY=cdc.test
SINK_TYPE=$1
CHANGEFEED_ID="weeklyrand"

RUN_SEED=${RUN_SEED:-1}
RUN_PROFILE=${RUN_PROFILE:-smoke}
RUN_DURATION=${RUN_DURATION:-3m}
DDL_DELAY_SEC=${DDL_DELAY_SEC:-3}

function build_runner() {
	mkdir -p "$WORK_DIR"
	go build -o "$WORK_DIR/random_ddl_test_runner" "$CUR/../../utils/random_ddl_test_runner"
}

function write_runner_config() {
	cat >"$WORK_DIR/runner_config.json" <<EOF
{
  "workdir": "$WORK_DIR",
  "profile": "$RUN_PROFILE",
  "seed": $RUN_SEED,
  "duration": "$RUN_DURATION",
  "upstream": { "host": "$UP_TIDB_HOST", "port": $UP_TIDB_PORT, "user": "root", "password": "" },
  "downstream": { "host": "$DOWN_TIDB_HOST", "port": $DOWN_TIDB_PORT, "user": "root", "password": "" },
  "cdc": {
    "addr": "127.0.0.1:8300",
    "user": "ticdc",
    "password": "ticdc_secret",
    "keyspace": "$KEYSPACE_NAME",
    "changefeed_id": "$CHANGEFEED_ID"
  },
  "sink_type": "$SINK_TYPE",
  "failover": { "enabled": false },
  "verify": {
    "health_interval": "10s",
    "no_advance_soft": "2m",
    "no_advance_hard": "10m",
    "converge_wait": "30s",
    "panic_patterns": ["panic", "fatal", "DATA RACE"],
    "log_scan_enabled": true,
    "fail_on_panic_match": true
  },
  "mysql": {
    "enabled": true,
    "diff_interval": "60s",
    "max_diff_checks": 1,
    "upstream_status_host": "$UP_TIDB_HOST",
    "upstream_status_port": $UP_TIDB_STATUS
  },
  "bootstrap": {
    "db_count": 5,
    "tables_per_db": 20,
    "base_rows_per_table": 100,
    "split_rows_per_table": 500,
    "frozen_rows_per_table": 50
  }
}
EOF
}

function cleanup() {
	set +e
	export GO_FAILPOINTS=''
	cleanup_process $CDC_BINARY >/dev/null 2>&1 || true
	stop_test $WORK_DIR
}

trap 'cleanup' EXIT

if [ "$SINK_TYPE" != "mysql" ]; then
	echo "Skip test since MySQL sink is required"
	exit 0
fi

rm -rf $WORK_DIR && mkdir -p $WORK_DIR

start_tidb_cluster --workdir $WORK_DIR

build_runner
write_runner_config

"$WORK_DIR/random_ddl_test_runner" --config "$WORK_DIR/runner_config.json" --phase bootstrap

run_sql "SET GLOBAL tidb_enable_external_ts_read = on;" ${DOWN_TIDB_HOST} ${DOWN_TIDB_PORT}

start_ts=$(run_cdc_cli_tso_query ${UP_PD_HOST_1} ${UP_PD_PORT_1})

export GO_FAILPOINTS="github.com/pingcap/ticdc/pkg/sink/mysql/MySQLSinkExecDDLDelay=return(\"$DDL_DELAY_SEC\")"
run_cdc_server --workdir $WORK_DIR --binary $CDC_BINARY

SINK_URI="mysql://root@127.0.0.1:3306/"
cdc_cli_changefeed create --start-ts=$start_ts --sink-uri="$SINK_URI" -c "$CHANGEFEED_ID" --config="$CUR/conf/changefeed_mysql.toml"

"$WORK_DIR/random_ddl_test_runner" --config "$WORK_DIR/runner_config.json" --phase workload

check_sync_diff $WORK_DIR "$WORK_DIR/diff_config.toml" 500

run_sql "SET GLOBAL tidb_enable_external_ts_read = off;" ${DOWN_TIDB_HOST} ${DOWN_TIDB_PORT}

echo "[$(date)] <<<<<< run test case $TEST_NAME success! >>>>>>"
