name: Integration-Mysql

on:
  push:
    branches:
      - master
      - "release-[0-9].[0-9]*"
    paths-ignore:
      - '**/*.md'
      - '**/OWNERS'
      - 'OWNERS'
      - 'OWNERS_ALIASES'

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
      - "release-[0-9].[0-9]*"
    paths-ignore:
      - '**/*.md'
      - '**/OWNERS'
      - 'OWNERS'
      - 'OWNERS_ALIASES'

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # # To boost the test speed, we split every 15 test cases into a group.
  e2e_test_group_1:
    ## Only run ci when PR is not draft
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest 
    name: E2E Test Group 1
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Integration Build
        run: |
          tests/scripts/download-integration-test-binaries.sh master true
          go build -o ./tools/bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl 
          make integration_test_build
          ls -l bin/ && ls -l tools/bin/

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_sources  

      - name: Upload test logs
        if: always()
        uses: ./.github/actions/upload-test-logs
        with:
          log-name: e2e_test_group_1

  # # To boost the test speed, we split every 15 test cases into a group.
  e2e_test_group_1_on_7-5:
    ## Only run ci when PR is not draft
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest 
    name: E2E Test Group 1 on 7.5
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Integration Build
        run: |
          tests/scripts/download-integration-test-binaries.sh master true v7.5.5
          go build -o ./tools/bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl 
          make integration_test_build
          ls -l bin/ && ls -l tools/bin/

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_sources

      - name: Upload test logs
        if: always()
        uses: ./.github/actions/upload-test-logs
        with:
          log-name: e2e_test_group_1_on_7.5

  e2e_test_group_2:
    ## Only run ci when PR is not draft
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest 
    name: E2E Test Group 2
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Integration Build
        run: |
          tests/scripts/download-integration-test-binaries.sh master true
          go build -o ./tools/bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl 
          make integration_test_build
          ls -l bin/ && ls -l tools/bin/

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_sources

      - name: Upload test logs
        if: always()
        uses: ./.github/actions/upload-test-logs
        with:
          log-name: e2e_test_group_2

  e2e_test_group_3:
    ## Only run ci when PR is not draft
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest 
    name: E2E Test Group 3
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.9.0
        with:
          provider: linode 

      - name: Run s3cmd command
        run: s3cmd --version

      - name: Integration Build
        run: |
          tests/scripts/download-integration-test-binaries.sh master true
          go build -o ./tools/bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl 
          make integration_test_build
          ls -l bin/ && ls -l tools/bin/

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source
      
      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_source

      - name: Test multi_source
        if: ${{ success() }}
        run: |
          export TICDC_NEWARCH=true && make integration_test CASE=multi_sources

      - name: Upload test logs
        if: always()
        uses: ./.github/actions/upload-test-logs
        with:
          log-name: e2e_test_group_3


  failover_e2e_test1:
      ## Only run ci when PR is not draft
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest 
    name: Failover E2E Test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Integration Build
        run: |
          tests/scripts/download-integration-test-binaries.sh master true
          go build -o ./tools/bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl 
          make integration_test_build
          ls -l bin/ && ls -l tools/bin/

      - name: Test fail_over
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over 
      
      - name: Test fail_over_ddl_A
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_A
      
      - name: Test fail_over_ddl_B
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_B
      
      - name: Test fail_over_ddl_C
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_C
      
      - name: Test fail_over_ddl_D
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_D

      - name: Test fail_over_ddl_E
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_E
      
      - name: Test fail_over_ddl_F
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_F
      
      - name: Test fail_over_ddl_G
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_G
      
      - name: Test fail_over_ddl_H
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_H

      - name: Test fail_over_ddl_I
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_I
      
      - name: Test fail_over_ddl_J
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_J

      - name: Test fail_over_ddl_K
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_K

      - name: Test fail_over_ddl_L
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_L
      
      - name: Test fail_over_ddl_M
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_M
          
      - name: Test fail_over_ddl_N
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_N

      - name: Test fail_over_ddl_O
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_O
      
      - name: Test fail_over_ddl_mix
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_mix 

      - name: Test fail_over_ddl_mix_with_syncpoint
        run: |
          pwd && ls -l bin/ && ls -l tools/bin/
          export TICDC_NEWARCH=true && make integration_test CASE=fail_over_ddl_mix_with_syncpoint 

      - name: Upload test logs
        if: always()
        uses: ./.github/actions/upload-test-logs
        with:
          log-name: failover_e2e_test1
