name: Integration Test (deprecated, only for debugging)

on:
  push:
    branches:
      - master
      - "release-[0-9].[0-9]*"
    paths-ignore:
      - '**/*.md'
      - '**/OWNERS'
      - 'OWNERS'
      - 'OWNERS_ALIASES'

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
      - "release-[0-9].[0-9]*"
    paths-ignore:
      - '**/*.md'
      - '**/OWNERS'
      - 'OWNERS'
      - 'OWNERS_ALIASES'

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  e2e_test_group_1:
    ## Only run ci when PR is not draft
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest 
    name: E2E Test Group
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      # - name: Integration Build
      #   run: |
      #     tests/scripts/download-integration-test-binaries.sh master true
      #     go build -o ./tools/bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl 
      #     make integration_test_build
      #     ls -l bin/ && ls -l tools/bin/

      # - name: Test charset_gbk
      #   run: |
      #     pwd && ls -l bin/ && ls -l tools/bin/
      #     export TICDC_NEWARCH=true && make integration_test CASE=charset_gbk 

      - name: Note
        run: |
          echo "Currently, we have migrated all integration tests to the self-hosted CI environment."
          echo "Only keep the boilerplate test group to facilitate future debugging."
          echo "For example, if we want to trigger certain test cases multiple times,"
          echo "we can use GitHub Actions as a convenient way to do so. You can achieve this by adding your"
          echo "test case to the group and pushing a PR to run them concurrently in the GitHub Actions environment."

      # - name: Upload test logs
      #   if: always()
      #   uses: ./.github/actions/upload-test-logs
      #   with:
      #     log-name: e2e_test_group_1
