// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/redo/writer/writer.go

// Package writer is a generated GoMock package.
package writer

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	event "github.com/pingcap/ticdc/pkg/common/event"
	writelease "github.com/pingcap/ticdc/pkg/writelease"
)

// MockRedoEvent is a mock of RedoEvent interface.
type MockRedoEvent struct {
	ctrl     *gomock.Controller
	recorder *MockRedoEventMockRecorder
}

// MockRedoEventMockRecorder is the mock recorder for MockRedoEvent.
type MockRedoEventMockRecorder struct {
	mock *MockRedoEvent
}

// NewMockRedoEvent creates a new mock instance.
func NewMockRedoEvent(ctrl *gomock.Controller) *MockRedoEvent {
	mock := &MockRedoEvent{ctrl: ctrl}
	mock.recorder = &MockRedoEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedoEvent) EXPECT() *MockRedoEventMockRecorder {
	return m.recorder
}

// PostFlush mocks base method.
func (m *MockRedoEvent) PostFlush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostFlush")
}

// PostFlush indicates an expected call of PostFlush.
func (mr *MockRedoEventMockRecorder) PostFlush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostFlush", reflect.TypeOf((*MockRedoEvent)(nil).PostFlush))
}

// ToRedoLog mocks base method.
func (m *MockRedoEvent) ToRedoLog() *event.RedoLog {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToRedoLog")
	ret0, _ := ret[0].(*event.RedoLog)
	return ret0
}

// ToRedoLog indicates an expected call of ToRedoLog.
func (mr *MockRedoEventMockRecorder) ToRedoLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToRedoLog", reflect.TypeOf((*MockRedoEvent)(nil).ToRedoLog))
}

// MockRedoLogWriter is a mock of RedoLogWriter interface.
type MockRedoLogWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRedoLogWriterMockRecorder
}

// MockRedoLogWriterMockRecorder is the mock recorder for MockRedoLogWriter.
type MockRedoLogWriterMockRecorder struct {
	mock *MockRedoLogWriter
}

// NewMockRedoLogWriter creates a new mock instance.
func NewMockRedoLogWriter(ctrl *gomock.Controller) *MockRedoLogWriter {
	mock := &MockRedoLogWriter{ctrl: ctrl}
	mock.recorder = &MockRedoLogWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedoLogWriter) EXPECT() *MockRedoLogWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedoLogWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedoLogWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedoLogWriter)(nil).Close))
}

// Run mocks base method.
func (m *MockRedoLogWriter) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockRedoLogWriterMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
<<<<<<< HEAD
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRedoLogWriter)(nil).Run), ctx)
=======
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRedoDMLWriter)(nil).Run), ctx)
}

// SetWriteGate mocks base method.
func (m *MockRedoDMLWriter) SetWriteGate(gate *writelease.Gate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWriteGate", gate)
}

// SetWriteGate indicates an expected call of SetWriteGate.
func (mr *MockRedoDMLWriterMockRecorder) SetWriteGate(gate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWriteGate", reflect.TypeOf((*MockRedoDMLWriter)(nil).SetWriteGate), gate)
}

// MockRedoDDLWriter is a mock of RedoDDLWriter interface.
type MockRedoDDLWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRedoDDLWriterMockRecorder
}

// MockRedoDDLWriterMockRecorder is the mock recorder for MockRedoDDLWriter.
type MockRedoDDLWriterMockRecorder struct {
	mock *MockRedoDDLWriter
}

// NewMockRedoDDLWriter creates a new mock instance.
func NewMockRedoDDLWriter(ctrl *gomock.Controller) *MockRedoDDLWriter {
	mock := &MockRedoDDLWriter{ctrl: ctrl}
	mock.recorder = &MockRedoDDLWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedoDDLWriter) EXPECT() *MockRedoDDLWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedoDDLWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedoDDLWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedoDDLWriter)(nil).Close))
>>>>>>> 46132a925 (server: fence capture writes with etcd and P2P leases (#6092))
}

// SetTableSchemaStore mocks base method.
func (m *MockRedoLogWriter) SetTableSchemaStore(arg0 *event.TableSchemaStore) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTableSchemaStore", arg0)
}

// SetTableSchemaStore indicates an expected call of SetTableSchemaStore.
func (mr *MockRedoLogWriterMockRecorder) SetTableSchemaStore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTableSchemaStore", reflect.TypeOf((*MockRedoLogWriter)(nil).SetTableSchemaStore), arg0)
}

<<<<<<< HEAD
// WriteEvents mocks base method.
func (m *MockRedoLogWriter) WriteEvents(ctx context.Context, events ...RedoEvent) error {
=======
// SetWriteGate mocks base method.
func (m *MockRedoDDLWriter) SetWriteGate(gate *writelease.Gate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWriteGate", gate)
}

// SetWriteGate indicates an expected call of SetWriteGate.
func (mr *MockRedoDDLWriterMockRecorder) SetWriteGate(gate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWriteGate", reflect.TypeOf((*MockRedoDDLWriter)(nil).SetWriteGate), gate)
}

// WriteDDLEvent mocks base method.
func (m *MockRedoDDLWriter) WriteDDLEvent(ctx context.Context, event *event.DDLEvent) error {
>>>>>>> 46132a925 (server: fence capture writes with etcd and P2P leases (#6092))
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range events {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteEvents", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteEvents indicates an expected call of WriteEvents.
func (mr *MockRedoLogWriterMockRecorder) WriteEvents(ctx interface{}, events ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, events...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteEvents", reflect.TypeOf((*MockRedoLogWriter)(nil).WriteEvents), varargs...)
}
