// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/redo/writer/writer.go

// Package writer is a generated GoMock package.
package writer

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	event "github.com/pingcap/ticdc/pkg/common/event"
)

// MockRedoEvent is a mock of RedoEvent interface.
type MockRedoEvent struct {
	ctrl     *gomock.Controller
	recorder *MockRedoEventMockRecorder
}

// MockRedoEventMockRecorder is the mock recorder for MockRedoEvent.
type MockRedoEventMockRecorder struct {
	mock *MockRedoEvent
}

// NewMockRedoEvent creates a new mock instance.
func NewMockRedoEvent(ctrl *gomock.Controller) *MockRedoEvent {
	mock := &MockRedoEvent{ctrl: ctrl}
	mock.recorder = &MockRedoEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedoEvent) EXPECT() *MockRedoEventMockRecorder {
	return m.recorder
}

// PostFlush mocks base method.
func (m *MockRedoEvent) PostFlush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostFlush")
}

// PostFlush indicates an expected call of PostFlush.
func (mr *MockRedoEventMockRecorder) PostFlush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostFlush", reflect.TypeOf((*MockRedoEvent)(nil).PostFlush))
}

// ToRedoLog mocks base method.
func (m *MockRedoEvent) ToRedoLog() *event.RedoLog {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToRedoLog")
	ret0, _ := ret[0].(*event.RedoLog)
	return ret0
}

// ToRedoLog indicates an expected call of ToRedoLog.
func (mr *MockRedoEventMockRecorder) ToRedoLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToRedoLog", reflect.TypeOf((*MockRedoEvent)(nil).ToRedoLog))
}

// MockRedoDMLWriter is a mock of RedoDMLWriter interface.
type MockRedoDMLWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRedoDMLWriterMockRecorder
}

// MockRedoDMLWriterMockRecorder is the mock recorder for MockRedoDMLWriter.
type MockRedoDMLWriterMockRecorder struct {
	mock *MockRedoDMLWriter
}

// NewMockRedoDMLWriter creates a new mock instance.
func NewMockRedoDMLWriter(ctrl *gomock.Controller) *MockRedoDMLWriter {
	mock := &MockRedoDMLWriter{ctrl: ctrl}
	mock.recorder = &MockRedoDMLWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedoDMLWriter) EXPECT() *MockRedoDMLWriterMockRecorder {
	return m.recorder
}

// AppendDMLEvents mocks base method.
func (m *MockRedoDMLWriter) AppendDMLEvents(ctx context.Context, events ...*event.RedoRowEvent) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range events {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AppendDMLEvents", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendDMLEvents indicates an expected call of AppendDMLEvents.
func (mr *MockRedoDMLWriterMockRecorder) AppendDMLEvents(ctx interface{}, events ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, events...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendDMLEvents", reflect.TypeOf((*MockRedoDMLWriter)(nil).AppendDMLEvents), varargs...)
}

// Close mocks base method.
func (m *MockRedoDMLWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedoDMLWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedoDMLWriter)(nil).Close))
}

// Run mocks base method.
func (m *MockRedoDMLWriter) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockRedoDMLWriterMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRedoDMLWriter)(nil).Run), ctx)
}

// MockRedoDDLWriter is a mock of RedoDDLWriter interface.
type MockRedoDDLWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRedoDDLWriterMockRecorder
}

// MockRedoDDLWriterMockRecorder is the mock recorder for MockRedoDDLWriter.
type MockRedoDDLWriterMockRecorder struct {
	mock *MockRedoDDLWriter
}

// NewMockRedoDDLWriter creates a new mock instance.
func NewMockRedoDDLWriter(ctrl *gomock.Controller) *MockRedoDDLWriter {
	mock := &MockRedoDDLWriter{ctrl: ctrl}
	mock.recorder = &MockRedoDDLWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedoDDLWriter) EXPECT() *MockRedoDDLWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedoDDLWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedoDDLWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedoDDLWriter)(nil).Close))
}

// SetTableSchemaStore mocks base method.
func (m *MockRedoDDLWriter) SetTableSchemaStore(arg0 *event.TableSchemaStore) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTableSchemaStore", arg0)
}

// SetTableSchemaStore indicates an expected call of SetTableSchemaStore.
func (mr *MockRedoDDLWriterMockRecorder) SetTableSchemaStore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTableSchemaStore", reflect.TypeOf((*MockRedoDDLWriter)(nil).SetTableSchemaStore), arg0)
}

// WriteDDLEvent mocks base method.
func (m *MockRedoDDLWriter) WriteDDLEvent(ctx context.Context, event *event.DDLEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteDDLEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteDDLEvent indicates an expected call of WriteDDLEvent.
func (mr *MockRedoDDLWriterMockRecorder) WriteDDLEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteDDLEvent", reflect.TypeOf((*MockRedoDDLWriter)(nil).WriteDDLEvent), ctx, event)
}
